version: '3'
volumes:
  static_files:
services:
  db:
    image: postgres
    ports:
      - "5436:5432"
    env_file:
      - docker/prod/.env
  web:
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    env_file:
      - docker/prod/.env
    command: gunicorn -w 4 main.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
      - static_files:/static_files
    depends_on:
      - db
    entrypoint: /entrypoint.sh