# Generated by Django 3.2.4 on 2021-06-22 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_file_id', models.BigIntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('duration_seconds', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('google_table_id', models.CharField(blank=True, max_length=255)),
                ('title_template', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('uid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('app_api_id', models.BigIntegerField()),
                ('app_api_hash', models.CharField(max_length=255)),
                ('app_title', models.CharField(blank=True, max_length=255)),
                ('app_short_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserToRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.radio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('uid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RadioChat',
            fields=[
                ('uid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.radio')),
            ],
        ),
        migrations.AddField(
            model_name='radio',
            name='telegram_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.telegramaccount'),
        ),
        migrations.CreateModel(
            name='QueueDownloadSoundCloud',
            fields=[
                ('sound_cloud_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('audio_file', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bot.audiofile')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField()),
                ('datetime_start', models.DateTimeField(blank=True)),
                ('audio_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.audiofile')),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.radio')),
            ],
        ),
    ]
